services:
  app:
    container_name: my_project_app
    build: ./    
    command: sh -c 'uvicorn main:app --host 0.0.0.0 --port 8000 --reload'
    environment:
      - DB_HOST=db
      - DB_NAME=database
      - DB_USER=${POSTGRES_DB_USER}
      - DB_PASS=${POSTGRES_DB_PASSWORD}
    volumes:
      - ./app:/app
    ports:
      - ${APP_HOST_PORT}:8000
    restart: always
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: my_project_postgres
    image: postgres
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
    ports:
      - ${POSTGRES_DB_HOST_PORT}:5432
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    restart: always

volumes:
  dev-db-data: