"""Modified User model

Revision ID: 73def93559b6
Revises: c3fbd0b1bc1d
Create Date: 2025-07-17 14:41:47.348343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73def93559b6'
down_revision: Union[str, Sequence[str], None] = 'c3fbd0b1bc1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('admin', 'manager', 'staff', name='user_role'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=sa.String(),
               type_=postgresql.ENUM('admin', 'manager', 'staff', name='user_role'),
               existing_nullable=False)
    # ### end Alembic commands ###
