"""Added Comment model

Revision ID: c3fbd0b1bc1d
Revises: 7b7d5f9d7673
Create Date: 2025-07-17 13:47:13.120183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3fbd0b1bc1d'
down_revision: Union[str, Sequence[str], None] = '7b7d5f9d7673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_role_enum = sa.Enum('admin', 'manager', 'staff', name='user_role')
    user_role_enum.create(op.get_bind())

    op.create_table('comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(),
               type_=user_role_enum,
               existing_nullable=False,
               postgresql_using="role::user_role")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=sa.Enum('admin', 'manager', 'staff', name='user_role'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_table('comment')
    sa.Enum(name='user_role').drop(op.get_bind())
    # ### end Alembic commands ###
